### ISSUE TITLE
Question: Regarding a simple installation of your development

### ISSUE THREAD

**Issue by ShmuelRonen** [nimadez/mental-diffusion#1]
I came across your project and it looks intriguing. But the installation you suggest is not clear to me.
Is there an installation method that will allow me to do it easily?

**Comment by nimadez** [comment]
Yes, the installation part has not been developed much, but I am sure better explanations and scripts to simplify the installation will be released soon.

**Comment by ShmuelRonen** [comment]
Could you update me when there will be a regulated installation process including a graphical UI that can be worked with comfortably?

**Comment by nimadez** [comment]
This program is made for personal use and shared on GitHub for free, so I don't think I have enough time to make a graphical installer, but in the next few days, an installer similar to the Voxel Builder installer will be released, so that it can be installed very easily with a few clicks, including the Python packages and checkpoint models.

**Comment by nimadez** [comment]
@ShmuelRonen a new one-click python installer has been added (models not included)
