### ISSUE TITLE
Error "Array with more than one element is ambiguous."

### ISSUE THREAD

**Issue by Hyphonic** [nimadez/mental-diffusion#12]
I got an error when running the cli version of this project.
My python version is 3.11
My Numpy version is 1.26.4
Please help and thanks in advance.
![Mental Diffusion](https://github.com/nimadez/mental-diffusion/assets/69310714/08c60b6e-269f-41d9-a9e9-9a547a1ad63d)

**Comment by nimadez** [comment]
The error does not appear to be related to the MD itself, as the checkpoint loading operation was completed successfully and inference was started. The reason can be the incompatibility of one of the Python packages.
I am looking for definitive answer, if your problem is solved please let me know.

**Comment by nimadez** [comment]
I reinstalled all the python packages with the **installer.py** script, only the **omegaconf** package was missing and was added, the cli test was successful on Windows, of course I can install the packages on Windows subsystem for Linux, but it seems unlikely that there will be a problem.

**Comment by nimadez** [comment]
MD does this automatically if there is no seed (-1), this problem is caused by **numpy** not generating the seed for some reason, but it seems that seed generation is difficult on different platforms, You have identified the problem and thank you. I definitely appreciate it, and if there's another problem, feel free to report it.
